### PR TITLE
Display log in Veeam depending on payload send success/failure

### PR DESCRIPTION
**Pull request by Philenst**
I had nothing good to put for the title. 

But this adds onto the existing function of sending notification to Veeam console depending on output.

If all were successful:
Sends message to console to say the script was successful
If some scripts fail:
Sends message to console that some sends were unsuccessful
If all scrips fail:
Sends message to console that all sends failed

@tigattack Appreciate any feedback as always.

### CODE REVIEW

**Review by Philenst — COMMENTED** [review]
Fix linter

**Review by tigattack — CHANGES_REQUESTED** [review]
`$hash` should have a less generic name. Perhaps `$svcStatus`, for example.

I'd like to optimise the conditionals on lines 406 and 409 somehow, but off the top of my head I can't think of anything right now, so that's just an minor todo for the future.

So, once `$hash` is renamed, I'm happy to merge.

**Comment by Philenst** [comment]
Renamed as per requested.

I also thought about lines 406 and 409 but I can't find any way to make it nicer.

**Review by tigattack — APPROVED** [review]
Thanks Phil.

**Pull request merged**
